# Generated by Django 6.0 on 2025-12-31 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_casedocument_customer'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cases_cus', to='customers.customer'),
            preserve_default=False,
        ),
    ]
