# Generated by Django 6.0 on 2026-01-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_alter_portfolio_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='created_source',
            field=models.CharField(choices=[('tenant', 'Tenant'), ('customer', 'Customer')], default='tenant', max_length=12),
        ),
    ]
