# Generated by Django 6.0 on 2026-01-09 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_case_created_source'),
        ('customers', '0002_customer_created_by_customer_portal_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='created_via',
            field=models.CharField(choices=[('tenant', 'Tenant'), ('customer_portal', 'Customer Portal')], db_index=True, default='tenant', max_length=30),
        ),
        migrations.AddField(
            model_name='debtor',
            name='source_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_debtors', to='customers.customer'),
        ),
    ]
