# Generated by Django 6.0 on 2026-04-10 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_casemessage_casemessageattachment_casemessageread_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiator_side', models.CharField(choices=[('tenant', 'Tenant'), ('customer', 'Customer')], default='tenant', max_length=12)),
                ('room_name', models.CharField(max_length=80, unique=True)),
                ('call_type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Vidéo')], default='video', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('ended', 'Terminé')], db_index=True, default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='cases.case')),
                ('initiator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['case', 'status'], name='cases_casec_case_id_41601b_idx')],
            },
        ),
    ]
