# Generated by Django 6.0 on 2025-12-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_roles_alter_role_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='libelle',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
