# Generated by Django 6.0 on 2025-12-28 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_role_libelle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='libelle',
        ),
    ]
