# Generated by Django 6.0 on 2025-12-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='code',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='is_active',
        ),
        migrations.AddField(
            model_name='tenant',
            name='plan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=12),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
