"""
Django settings for acx project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!8$9hbz5r@g-o$6$ol=6__+f19&tfymlcw&@jb8c1g%=yf-o$c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Django …
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # DRF + CORS
    "rest_framework",
    "corsheaders",
    "rest_framework.authtoken",

    # SimpleJWT + Blacklist
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "django_filters",
    # Apps projet
    "accounts",
    "tenancy",
    "cases",
    "customers",
    "collections_management"
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "django_filters.rest_framework.DjangoFilterBackend",
    ),
}

ROOT_URLCONF = 'acx.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'acx.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',  # Ou 'django.db.backends.postgresql_psycopg2'
        'NAME': 'acx_db',
        'USER': 'postgres',
        'PASSWORD': '1651221@$Ng',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


AUTH_USER_MODEL = "accounts.User"

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=200),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}


FRONTEND_BASE_URL = "http://localhost:3000"   # ou http://localhost:3000

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# Upload limits
ACX_CP_MAX_FILE_MB = 10
ACX_CP_MAX_TOTAL_MB = 20

# Optional: base url for email links
FRONTEND_CLIENT_PORTAL_BASE_URL = "http://localhost:3000/fr"  # ou sans /fr si tu gères autrement


# ---- ACX collections management ----
ACX_TENANT_MODEL = "tenancy.Tenant"              # ton Tenant
ACX_PORTFOLIO_MODEL = "cases.Portfolio"     # ton Portfolio
ACX_DEBTOR_MODEL = "customers.Customer"


"""

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'ubagroup.com'      # à confirmer avec cPanel (ou smtp.it-expertises.com si dispo)
EMAIL_PORT = 25
EMAIL_USE_SSL = True                  # IMPORTANT pour port 465
EMAIL_USE_TLS = False
EMAIL_HOST_USER = 'ubachad.creditnotify@ubagroup.com'
EMAIL_HOST_PASSWORD = 'Venice@678'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER"""


"""'EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'"""
EMAIL_BACKEND = "core.email_backend.InsecureEmailBackend"




DEFAULT_FROM_EMAIL = "acx@acremac.com"
SERVER_EMAIL = "acx@acremac.com"

EMAIL_HOST_USER = "acx@acremac.com"
EMAIL_HOST_PASSWORD = 'v4>&3k=71Z+"'
EMAIL_HOST = "3.236.213.114"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False