# Generated by Django 6.0 on 2026-02-05 09:30

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collections_management', '0003_alter_collectionemail_options_and_more'),
        ('customers', '0003_supportticket_supportticketmessage_and_more'),
        ('tenancy', '0003_tenant_address_line1_tenant_address_line2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasuryAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('bank', 'Banque'), ('cash', 'Caisse'), ('mobile_money', 'Mobile Money'), ('other', 'Autre')], default='bank', max_length=20)),
                ('currency', models.CharField(default='XAF', max_length=3)),
                ('is_default', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_treasury_accounts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasury_accounts', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RemittanceBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='XAF', max_length=3)),
                ('amount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('validated', 'Validé'), ('paid', 'Payé'), ('cancelled', 'Annulé')], default='draft', max_length=20)),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_remittances', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remittances', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remittances', to='tenancy.tenant')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remittances', to='treasury_management.treasuryaccount')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TreasuryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Entrée'), ('out', 'Sortie')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('cancelled', 'Annulé')], default='confirmed', max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('currency', models.CharField(default='XAF', max_length=3)),
                ('value_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('source', models.CharField(choices=[('payment', 'Paiement'), ('remittance', 'Reversement client'), ('manual', 'Manuel'), ('other', 'Autre')], default='manual', max_length=20)),
                ('source_key', models.CharField(blank=True, max_length=120, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='treasury_management.treasuryaccount')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_movements', to='collections_management.collectioncase')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_treasury_movements', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_movements', to='customers.customer')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_movements', to='collections_management.payment')),
                ('remittance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_movements', to='treasury_management.remittancebatch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasury_movements', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-value_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RemittanceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='remittance_lines', to='collections_management.collectioncase')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remittance_lines', to='collections_management.payment')),
                ('remittance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='treasury_management.remittancebatch')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('remittance', 'payment'), name='uniq_remittance_payment')],
            },
        ),
        migrations.AddConstraint(
            model_name='treasuryaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('tenant', 'currency'), name='uniq_default_treasury_account_per_currency'),
        ),
        migrations.AddConstraint(
            model_name='treasurymovement',
            constraint=models.UniqueConstraint(condition=models.Q(('source_key__isnull', False)), fields=('tenant', 'source_key'), name='uniq_treasury_source_key'),
        ),
    ]
